pep-mysql:
  image: mysql
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
    - ./mysql/init:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=pep
    - MYSQL_USER=pep
    - MYSQL_PASSWORD=pep
# Could deploy mongo shard cluster using https://github.com/propersoft-cn/docker-mongo-shard-cluster
pep-mongo:
  image: mongo:3.6.5
  entrypoint: /code/devops/current/mongoEp.sh
  volumes:
    - ./mongo/data:/data/db
    - ./mongo/devops/:/code/devops/current/
pep-redis:
  image: redis:5.0.0
  volumes:
    - ./redis/data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
pep-server:
  image: propersoft/docker-jre:8u171-jre
  volumes:
    - ./pep/app:/usr/local/pep/app
    - ./pep/logs:/usr/local/pep/logs
  links:
    - pep-mongo:mongo
    - pep-mysql:mysql
    - pep-redis:redis
  environment:
    - JAVA_OPTS=-server -Xms512m -Xmx4096m
  command: java -Xbootclasspath/p:/usr/lib/alpn-boot-8.1.12.v20180117.jar -jar /usr/local/pep/app/pep.jar
pep-nginx:
  image: nginx:1.13.7
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/dhparams.pem:/etc/nginx/dhparams.pem
  links:
    - pep-server:pep
  ports:
    - "8080:80"
